name: Auto Assign to Project(s)

on:
  pull_request:
    types: [ opened ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign PR to project
    steps:
      - name: Assign new pull requests to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          github.event.action == 'opened' &&
          ! contains(github.event.pull_request.labels.*.name, 'invalid')
        with:
          project: 'https://github.com/ChevryGames/cg-math/projects/1'